{"name": "Login_No.002_登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_pytest.test_allure_demo.test_allure_demo.TestLoginMoudel object at 0x0000029C8773D580>\n\n>   ???\nE   assert False\n\nE:\\pytestProject\\test_allure_demo\\test_allure_demo.py:15: AssertionError"}, "start": 1641306488416, "stop": 1641306488417, "uuid": "b92645df-a519-41d1-aa3b-8b989234354a", "historyId": "6a2d2900137c956db240aed8cb9a9596", "testCaseId": "4b6ec69df0cf35b98289ec63c4355d97", "fullName": "test_allure_demo.TestLoginMoudel#test_login_success", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录成功"}, {"name": "suite", "value": "test_allure_demo"}, {"name": "subSuite", "value": "TestLoginMoudel"}, {"name": "host", "value": "DESKTOP-5N5QG51"}, {"name": "thread", "value": "2052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_demo"}]}